1. Import Libraries
2. Load Processed Dataset
3. Review Train-Test Data
4. Build Baseline Model (Linear Regression)
5. Make Predictions
6. Evaluate Model
7. Visualize Results
8. Business Interpretation

In [24]:
# import Libraries
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

import joblib

import warnings
warnings.filterwarnings("ignore")

In [25]:
# Load Dataset
df= pd.read_csv("../output/insurance_with_bmi.csv")
df.head()

   Age  Diabetes  ...  PremiumPrice        BMI
0   45         0  ...         25000  23.725286
1   60         1  ...         29000  22.530864
2   36         1  ...         23000  23.634033
3   52         1  ...         28000  27.770313
4   38         0  ...         23000  31.934969

[5 rows x 12 columns]

In [26]:
df.columns

Index(['Age', 'Diabetes', 'BloodPressureProblems', 'AnyTransplants',
       'AnyChronicDiseases', 'Height', 'Weight', 'KnownAllergies',
       'HistoryOfCancerInFamily', 'NumberOfMajorSurgeries', 'PremiumPrice',
       'BMI'],
      dtype='str')

In [27]:
# Prepare data
features = [col for col in df.columns if col != "PremiumPrice"]
    
X = df[features]
y = df["PremiumPrice"]

In [28]:
# Split the dataset into features and target variable
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [29]:
# Reusable Model Evaluation Function

def evaluate_model(model, X_train, X_test, y_train, y_test):
    
    # Train the model
    model.fit(X_train, y_train)
    
    # Make predictions
    predictions = model.predict(X_test)
    
    # Calculate metrics
    mae = mean_absolute_error(y_test, predictions)
    rmse = np.sqrt(mean_squared_error(y_test, predictions))
    r2 = r2_score(y_test, predictions)
    
    return mae, rmse, r2

## Baseline Model (Linear Regression)

In [34]:
# Linear Regression Evaluation
lr_mae, lr_rmse, lr_r2 = evaluate_model(lr, X_train, X_test, y_train, y_test)

print("Linear Regression Results")
print("MAE :", lr_mae)
print("RMSE:", lr_rmse)
print("R² :", lr_r2)

Linear Regression Results
MAE : 2586.1817100200624
RMSE: 3494.413798189816
R² : 0.713646143964974

# Ridge Regression

In [35]:
# Create Ridge model
ridge_model = Ridge(alpha=1.0)

# Evaluate
ridge_mae, ridge_rmse, ridge_r2 = evaluate_model(
    ridge_model,
    X_train,
    X_test,
    y_train,
    y_test
)

print("Ridge Regression Results")
print("MAE :", ridge_mae)
print("RMSE:", ridge_rmse)
print("R²  :", ridge_r2)

Ridge Regression Results
MAE : 2591.7875393764652
RMSE: 3501.4499746716256
R²  : 0.7124918074321824

# Lasso Regression

In [36]:
# Create Lasso model
lasso_model = Lasso(alpha=0.1)

# Evaluate
lasso_mae, lasso_rmse, lasso_r2 = evaluate_model(
    lasso_model,
    X_train,
    X_test,
    y_train,
    y_test
)

print("Lasso Regression Results")
print("MAE :", lasso_mae)
print("RMSE:", lasso_rmse)
print("R²  :", lasso_r2)

Lasso Regression Results
MAE : 2586.2666878583527
RMSE: 3494.5394500647435
R²  : 0.7136255502128422

# Decision Tree

In [38]:
# Decision Tree
dt_mae, dt_rmse, dt_r2 = evaluate_model(
    DecisionTreeRegressor(random_state=42),
    X_train,
    X_test,
    y_train,
    y_test
)

print("Decision Tree Results")
print("MAE :", dt_mae)
print("RMSE:", dt_rmse)
print("R²  :", dt_r2)

Decision Tree Results
MAE : 1287.878787878788
RMSE: 4008.1986684365543
R²  : 0.6232503553124596

# Random Forest Regressor

In [39]:
# Random Forest Regressor
# Create Random Forest model
rf_model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

# Evaluate
rf_mae, rf_rmse, rf_r2 = evaluate_model(
    rf_model,
    X_train,
    X_test,
    y_train,
    y_test
)

print("Random Forest Results")
print("MAE :", rf_mae)
print("RMSE:", rf_rmse)
print("R²  :", rf_r2)

Random Forest Results
MAE : 1010.3535353535353
RMSE: 2135.170728631329
R²  : 0.8930896905551489

# Gradient Boosting Regressor

In [40]:
# Gradient Boosting Regressor
gb_model = GradientBoostingRegressor(random_state=42)

# Evaluate
gb_mae, gb_rmse, gb_r2 = evaluate_model(
    gb_model,
    X_train,
    X_test,
    y_train,
    y_test
)

print("Gradient Boosting Results")
print("MAE :", gb_mae)
print("RMSE:", gb_rmse)
print("R²  :", gb_r2)

Gradient Boosting Results
MAE : 1522.1539686511899
RMSE: 2382.7538984583052
R²  : 0.8668587131846058

# Model Comparison

In [41]:
# Model Comparison

results = pd.DataFrame({
    "Model": [
        "Linear Regression",
        "Ridge Regression",
        "Lasso Regression",
        "Decision Tree",
        "Random Forest",
        "Gradient Boosting"
    ],
    "MAE": [
        lr_mae,
        ridge_mae,
        lasso_mae,
        dt_mae,
        rf_mae,
        gb_mae
    ],
    "RMSE": [
        lr_rmse,
        ridge_rmse,
        lasso_rmse,
        dt_rmse,
        rf_rmse,
        gb_rmse
    ],
    "R2_Score": [
        lr_r2,
        ridge_r2,
        lasso_r2,
        dt_r2,
        rf_r2,
        gb_r2
    ]
})

# Sort by R² score (higher is better)
results = results.sort_values(by="R2_Score", ascending=False)

results

               Model          MAE         RMSE  R2_Score
4      Random Forest  1010.353535  2135.170729  0.893090
5  Gradient Boosting  1522.153969  2382.753898  0.866859
0  Linear Regression  2586.181710  3494.413798  0.713646
2   Lasso Regression  2586.266688  3494.539450  0.713626
1   Ridge Regression  2591.787539  3501.449975  0.712492
3      Decision Tree  1287.878788  4008.198668  0.623250

In [42]:
# Automatically Select the Best Model

best_model_name = results.iloc[0]["Model"]
print("Best Model:", best_model_name)

Best Model: Random Forest

In [43]:
# Train the final Random Forest model
final_model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

final_model.fit(X_train, y_train)

# Save the model
joblib.dump(final_model, "../models/insurance_premium_model.pkl")

print("Model saved successfully!")

Model saved successfully!

## Professional Summary

Multiple machine learning models were trained and evaluated on the insurance premium dataset.The models were compared using consistent evaluation metrics, and the best-performing model was selected for further analysis and deployment.

Best Model: Random Forest

The trained model has been saved as insurance_premium_model.pkl and will be used in the Streamlit web application developed in the later stages of the project.